version: 2.1

commands:
   print_pipeline_id:
    description: "Just Testing Command"
    parameters:
      to:
        type: string
        default: "Hello This is my circle ci"
    steps:
      - run: echo  "Hello, This is my circle ci id <<parameters.to>>"

jobs:
  cicd_workflow:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: "echo Hello printing CircleCI Workflow"
      - run: 
          name: "PROJECT ENVIRONMENT VARIABLE ID"
          command: echo $TEST_ENV_VAR
      - run:
          name: "CIRCLE BRANCH"
          command: echo ${CIRCLE_BRANCH}
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: echo "Hello, building project"
      - run:
          name: "Building project"
          command: npm run lint

  # test:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run: npm i
  #     - run: echo "Hello, testing project"
  #     - run:
  #         name: "Testing project"
  #         command: npm run test

  # analyze:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run: echo "Hello, first analyze"
  #     - run:
  #         name: "Building project"
  #         command: npm audit
  #     - run:
  #         name: on error
  #         command: echo "Hello, Error occured when analyzing"
  #         when: on_fail

workflows: 
  first_pipeline_workflow:
    jobs:
      - cicd_workflow
      - build
      # - test:
      #     requires:
      #       - build
      # - analyze:
      #     requires:
      #       - test 





