version: 2.1

commands:
   print_pipeline_id:
    description: "Just Testing Command"
    parameters:
      to:
        type: string
        default: "Hello This is my circle ci"
    steps:
      - run: echo  "Hello, This is my circle ci id <<parameters.to>>"

jobs:
  compile:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello, first compile"

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello, first test"

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello, first analysis"

workflows: 
  first_pipeline_workflow:
    jobs:
      - compile





